### ISSUE TITLE
[API][CD] Automate deployment to a remote server using Ansible

### ISSUE THREAD

**Issue by mihamieat** [mihamieat/gpac-api#26]
# 1. Workflow Overview
GitHub Actions:
- Build and push the Docker image to a registry (Docker Hub, AWS ECR, or GitHub Container Registry).
- Trigger Ansible to deploy the new image to the remote server.
Ansible Playbook:
- Connect to the remote server via SSH.
- Pull the latest Docker image.
- Restart the container.
# 2. GitHub Actions Workflow
Create .github/workflows/deploy.yml:

```
name: Deploy to Remote Server

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and push Docker image
      - name: Build and push Docker image
        id: build_image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: myorg/myapp:latest

      # 4. Deploy using Ansible
      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [web]
            ${{ secrets.REMOTE_HOST }} ansible_user=${{ secrets.REMOTE_USER }}
```
# 3. Ansible Playbook (ansible/deploy.yml)
Create ansible/deploy.yml:
```

- name: Deploy Docker App
  hosts: web
  become: yes
  tasks:
    - name: Pull latest Docker image
      command: docker pull myorg/myapp:latest

    - name: Stop and remove existing container
      command: docker rm -f myapp_container
      ignore_errors: yes

    - name: Run new container
      command: >
        docker run -d --name myapp_container
        -p 80:80 myorg/myapp:latest
```
# 4. Secrets Configuration
Go to **GitHub** → **Settings** → **Secrets and variables** → **Actions** → **New repository secret** and add:

```
DOCKER_USERNAME: Your Docker Hub username.
DOCKER_PASSWORD: Your Docker Hub password.
SSH_PRIVATE_KEY: The private SSH key for Ansible to connect to your server.
REMOTE_HOST: The IP or hostname of your remote server.
REMOTE_USER: The SSH username.
```
# 5. Configure the Remote Server
Ensure your remote server:

Has Docker installed.
Allows SSH access from GitHub Actions.
Has your public key (~/.ssh/authorized_keys) to allow Ansible to connect.
# 6. Commit & Push
Commit the files and push to develop:

```
git add .
git commit -m "Automated deployment setup"
git push origin develop
```
